### ISSUE TITLE
"Machine Zone" Title is not being created.

### ISSUE THREAD

**Issue by AdamSearsLOTO** [Geppo86/LOTO#9]
While trying to create a new machine zone, the entity was created, but after hitting create, the name did not display. I clicked 'edit' and was able to go to the edit screen, but both the name and map were null entries. I (seemingly) successfully deleted the machine zones afterwards.

**Comment by Geppo86** [comment]
Solved. Added also more column for the model.

**Comment by AdamSearsLOTO** [comment]
Complete!

**Comment by AdamSearsLOTO** [comment]
Correction. For some reason it initially showed complete, but now has disappeared. The Machine zone titles are still an issue.
